server:
  port: 9321

#log
logging:
  config: classpath:logback-spring.xml

spring:
  main:
    allow-bean-definition-overriding: true




#kafka配置
kafka:
  bootstrap:
    server: 10.0.
  report:
    topic: IDS
    groupId: operation-dev
    auto:
      offset:
        reset: earliest

redis:
  job:
    application:
      host: 192.168.117.128
      port: 6379
      password: cjc1573
      timeout: 2000
      index: 1
      workModel: single

elasticjob:
  regCenter:
    serverLists: localhost:6181
    namespace: mall-job-application
  tracing:
    type: RDB
  jobs:
    jobErrorHandlerType: EMAIL
  props:
    email:
      host: host
      port: 465
      username: username
      password: password
      useSsl: true
      subject: ElasticJob error message
      from: from@xxx.xx
      to: to1@xxx.xx,to2@xxx.xx
      cc: cc@xxx.xx
      bcc: bcc@xxx.xx
      debug: false