server:
  port: 9600

#log
logging:
  config: classpath:logback-spring.xml

spring:
  main:
    allow-bean-definition-overriding: true

mysql:
  job:
    dataSource:
      url: jdbc:mysql://192.168.117.130:3306/sp_job?useUnicode=true&characterEncoding=utf-8&useSSL=false
      userName: root
      password: cjc1573
      driverClassName: com.mysql.cj.jdbc.Driver
      validationQuery: select 1
      maxPoolSize: 30




#kafka配置
kafka:
  bootstrap:
    server: 10.0.
  report:
    topic: IDS
    groupId: operation-dev
    auto:
      offset:
        reset: earliest

redis:
  job:
    application:
      host: 192.168.117.128
      port: 6379
      password: cjc1573
      timeout: 2000
      index: 1
      workModel: single

elasticjob:
  zookeeper:
    serverLists: 192.168.117.128:2181,192.168.117.129:2181,192.168.117.130:2181
    namespace: mall-job-application