server:
  port: 9321

#log
logging:
  config: classpath:logback-spring.xml

spring:
  main:
    allow-bean-definition-overriding: true


dubbo:
  application:
    name: member-application-consumer
  consumer:
    check: false
  registry:
    address: zookeeper://192.168.117.128:2181,192.168.117.129:2181,192.168.117.130:2181
    ##address: N/A
    file: dubbo-registry/dubbo-registry.properties
    check: false
  protocol:
    name: dubbo
    port: 20880
  reference:
    loadbalance: roundrobin

#kafka配置
kafka:
  bootstrap:
    server: 10.0.
  report:
    topic: IDS
    groupId: operation-dev
    auto:
      offset:
        reset: earliest

redis:
  member:
    application:
      host: 192.168.117.128
      port: 6379
      password: cjc1573
      timeout: 2000
      index: 1
      workModel: single