server:
  port: 9400

#log
logging:
  config: classpath:logback-spring.xml

mall-item-center:
  ribbon:
    ConnectTimeout: 250 #单位ms,请求连接超时时间
    ReadTimeout: 1000 #单位ms,请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数

spring:
  application:
    name: mall-member-center
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.117.128:8848,192.168.117.129:8848,192.168.117.130:8848
      config:
        server-addr: 192.168.117.128:8848,192.168.117.129:8848,192.168.117.130:8848
        file-extension: yaml

#kafka配置
kafka:
  bootstrap:
    server: 10.0.
  report:
    topic: IDS
    groupId: operation-dev
    auto:
      offset:
        reset: earliest

redis:
  manager:
    application:
      host: 192.168.117.128
      port: 6379
      password: cjc1573
      timeout: 2000
      index: 4
      workModel: single