server:
  port: 8500

#log
logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: mall-promotion-center
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.117.128:8848,192.168.117.129:8848,192.168.117.130:8848
      config:
        server-addr: 192.168.117.128:8848,192.168.117.129:8848,192.168.117.130:8848
        file-extension: yaml

mysql:
  promotion:
    dataSource:
      url: jdbc:mysql://192.168.117.130:3306/sp_promotion?useUnicode=true&characterEncoding=utf-8&useSSL=false
      userName: root
      password: cjc1573
      driverClassName: com.mysql.cj.jdbc.Driver
      validationQuery: select 1
      maxPoolSize: 30




#kafka配置
kafka:
  bootstrap:
    server: 10.0.
  report:
    topic: IDS
    groupId: operation-dev
    auto:
      offset:
        reset: earliest

redis:
  promotion:
    center:
      host: 192.168.117.128
      port: 6379
      password: cjc1573
      timeout: 2000
      index: 1
      workModel: single
